project:
  type: website
  output-dir: docs

website:
  title: "Yee Ching's Website"
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - finalproject.qmd
      
format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual




