---
title: "Final Project"
---

# What makes K-Dramas so popular globally?


## Introduction

```{r, eval=TRUE, echo=FALSE}

suppressMessages({
  suppressWarnings({
    library(ggplot2)
    library(RColorBrewer)
    library(plotly, warn.conflicts = FALSE)
    

# Read the CSV file
kdrama_pop_2022 <- read.csv("datasets/k-drama-popularity-worldwide-2022.csv", fill=TRUE)

# Define custom order for the levels of the "Popularity" variable
popularity_order <- c("Very popular", "Moderately popular", "Slightly popular", "Not popular")
kdrama_pop_2022$Popularity <- factor(kdrama_pop_2022$Popularity, levels = popularity_order)

# Create a vector of colors for the bars
colors <- brewer.pal(4, "Set2") 

# Create the bar plot with specified colors and custom order
bp1 <- ggplot(kdrama_pop_2022, aes(x = Popularity, y = Percentage, fill = Popularity)) +
  geom_bar(stat = "identity") +
  labs(title = "K-Drama Popularity Worldwide in 2022", x = "Popularity", y = "Percentage", caption = "Source: Statista") +
  theme_bw() +
  scale_fill_manual(values = colors)

ggplotly(bp1)

  })
})
```

```{r, eval=FALSE, echo=FALSE}
kdrama <- read.csv("kor_drama.csv")

```

test test test 

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://yeech1ng.shinyapps.io/sample_app/ "> </iframe>
```