---
title: "Week 8 Project Submission"
author: "Wong Yee Ching"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Finalised Topic

The topic that I have selected is on Korean Dramas, also known as K-Dramas, and the question of, “What makes K-Drama popular?”. Through a factors-type data-story, I will explain the popularity of K-Dramas by analysing and showcasing the specific factors that have contributed to its popularity.

## 2. Data Sources

These are the data sources that I have curated so far:

1.  K-Drama’s degree of popularity worldwide as of December 2022: <https://www.statista.com/statistics/999239/south-korea-korean-drama-popularity-worldwide/> 

2. America 2019: <https://www-statista-com.libproxy1.nus.edu.sg/statistics/1017862/south-korea-korean-drama-popularity-us/> 

3. Japan 2019: <https://www-statista-com.libproxy1.nus.edu.sg/statistics/1017819/south-korea-korean-drama-popularity-japan/> 

4. Thailand 2019: <https://www-statista-com.libproxy1.nus.edu.sg/statistics/1017828/south-korea-korean-drama-popularity-thailand/> 

5. China 2019: <https://www-statista-com.libproxy1.nus.edu.sg/statistics/1017829/south-korea-korean-drama-popularity-china/> 

6. Russia 2019: <https://www-statista-com.libproxy1.nus.edu.sg/statistics/1017888/south-korea-korean-drama-popularity-russia/>

7. Top 100 K-Dramas users have ranked on MyDramaList, featuring variables like Name, Year of Release, Aired Date, Aired On, Number of Episode, Network, Duration, Content Rating, Synopsis, Cast, Genre, Tags, Rank, Rating: <https://www.kaggle.com/datasets/chanoncharuchinda/top-100-korean-drama-mydramalist>

8.  Information about dramas (Drama Name, Year, Synopsis, Genres, Tags, Director, Screen writer, Country ect) and user reviews (Ratings on the story, Acting cast, Music, Rewatch Value, Overall, Number of episodes watched etc) from Korea, Japan, and Thailand, which may be useful for comparison across countries: <https://www.kaggle.com/datasets/chanoncharuchinda/thai-and-japanese-drama-vs-korean-drama-dominance?select=kor_user_reviews.csv>

9.  Top 5000 Asian Dramas from Korea, Japan, China, Taiwan, and Thailand, featuring variables like Name, Episodes, Released Year, Language, Rating, Ranking: <https://www.kaggle.com/datasets/lakshmiindukosuri/top-5000-dramas-1983-2023>

10.  Popular over the top media services for accessing K-Dramas worldwide in 2022: <https://www-statista-com.libproxy1.nus.edu.sg/statistics/999315/south-korea-ott-services-for-accessing-korean-dramas-worldwide/>
